### ISSUE TITLE
ProxyJump not working

### ISSUE THREAD

**Issue by FelipeMiranda** [flyingrhinonz/nccm#23]
```
dev-bastion:
  comment: Dev Bastion
  address: <Bastion Public IP>
  user: <user>
  keepalive: 25
  identity: ~/.ssh/id_rsa
  port: 22
  forwardAgent: yes
  logLevel: INFO
  
dev-api:
  comment: dev api1
  address: <PRIVATE IP>
  user: <user>
  keepalive: 25
  identity: ~/.ssh/id_rsa
  port: 22
  forwardAgent: yes
  logLevel: INFO
  ProxyJump: dev-bastion
  
 ➜  ~ nccm dev-api

nccm: About to ssh using:
ssh <user>@<PRIVATE IP> -p 22 -o ServerAliveInterval=25 -i ~/.ssh/id_rsa

Connecting...
```
